apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: data-admin-ch

commonLabels:
  app.kubernetes.io/instance: data.admin.ch
  app.kubernetes.io/name: trifid

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
